server:
  port: 8080
spring:
  application:
    name: gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
security:
  basic:
    enable: false
zuul:
  host:
    socket-timeout-millis: 30000
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: DEBUG
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
spring:
  profiles: docker
logging:
  level:
    root: INFO